var goog;
var encodeURIComponent;
var decodeURIComponent;
Window.prototype.setTimeout;
Object.toBase64;
Object.toArrayBuffer;
Object.exec;
Object.index;
Object.install;
Int8Array.prototype.set;
Int8Array.prototype.fill;
Int8Array.prototype.length;
var Buffer;
var ByteBuffer;
var ByteBufferPrototype;
ByteBufferPrototype.readBitSet;
ByteBuffer.wrap;
ByteBuffer.fromBase64;
goog.global;
goog.isArrayLike;
goog.string;
goog.string.StringBuffer;
goog.string.StringBuffer.prototype.append;
var process;
process.hrtime;
JSON.parse;
JSON.stringify;
var require;
Uint8Array.prototype.length;
var module;
module.exports;
RegExp.prototype.camel_snake_kebab$internals$string_separator$StringSeparator$;
RegExp.prototype.camel_snake_kebab$internals$string_separator$StringSeparator$split$arity$2;
RegExp.prototype.schema$core$Schema$;
RegExp.prototype.schema$core$Schema$spec$arity$1;
RegExp.prototype.schema$core$Schema$explain$arity$1;
