var encodeURIComponent;
var decodeURIComponent;
Window.prototype.setTimeout;
Object.toBase64;
Object.toArrayBuffer;
Object.readUTF8String;
Object.exec;
Object.index;
Object.install;
Int8Array.prototype.buffer;
Int8Array.prototype.set;
Int8Array.prototype.fill;
Int8Array.prototype.length;
var ByteBufferPrototype;
ByteBufferPrototype.readBitSet;
var ByteBuffer;
ByteBuffer.calculateUTF8Bytes;
ByteBuffer.prototype.offset;
ByteBuffer.prototype.skip;
ByteBuffer.METRICS_BYTES;
ByteBuffer.wrap;
ByteBuffer.fromBase64;
ByteBuffer.fromUTF8;
var goog;
goog.global;
goog.isArrayLike;
goog.string;
goog.string.StringBuffer;
goog.string.StringBuffer.prototype.append;
var process;
process.hrtime;
JSON.stringify;
var require;
Uint8Array.prototype.length;
var module;
module.exports;
RegExp.prototype.camel_snake_kebab$internals$string_separator$StringSeparator$;
RegExp.prototype.camel_snake_kebab$internals$string_separator$StringSeparator$split$arity$2;
RegExp.prototype.schema$core$Schema$;
RegExp.prototype.schema$core$Schema$spec$arity$1;
RegExp.prototype.schema$core$Schema$explain$arity$1;
var Long;
Long.fromBits;
Long.fromString;
