var encodeURIComponent;
var decodeURIComponent;
Window.prototype.setTimeout;
Object.out;
Object.out.println;
Object.error;
Object.error.println;
Object.exec;
Object.index;
Object.install;
Int8Array.prototype.set;
Int8Array.prototype.fill;
Int8Array.prototype.length;
Int8Array.prototype.slice;
var goog;
goog.global;
goog.isArrayLike;
goog.string;
goog.string.StringBuffer;
goog.string.StringBuffer.prototype.append;
var process;
process.hrtime;
JSON.stringify;
JSON.parse;
var require;
Uint8Array.prototype.length;
var setTimeout;
RegExp.prototype.camel_snake_kebab$internals$string_separator$StringSeparator$;
RegExp.prototype.camel_snake_kebab$internals$string_separator$StringSeparator$split$arity$2;
RegExp.prototype.schema$core$Schema$;
RegExp.prototype.schema$core$Schema$spec$arity$1;
RegExp.prototype.schema$core$Schema$explain$arity$1;
var Java;
Java.type;
